import "FileBrowserViewModel.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass FileBrowserPane : Windows.UI.Xaml.Controls.UserControl
    {
        FileBrowserPane();
        FileBrowserViewModel ViewModel { get; };
    };
}
